podcast:
  title: Die Marcologie
  description: Ein Podcast der sich aus dem Namen Marc und Anthologie zusammensetzt und verschiedene Episoden mit verschiedenen Themen beinhaltet
  url: /podcast.xml
  author: Marc Retz
  email: marc@mrcsrv.de
  logo: images/cover.png
  language: de
  category: Comedy
  subcategory: Stand-Up
  type: episodic # episodic | serial
  explicit: true # true | false
  complete: no # 'yes' | 'no'
  block: no # 'yes' | 'no'
